package zjmbg

var (
	jmbgRegions = map[string]JMBGRegion{
		"70": {
			Name: "Diplomatsko-konzularno predstavništvo u inostranstvu",
		},
		"71": {
			Name:           "Beograd",
			Municipalities: []string{"Beograd"},
		},
		"72": {
			Name: "Šumadija i Pomoravlje",
			Municipalities: []string{
				"Aranđelovac",
				"Batočina",
				"Despotovac",
				"Jagodina",
				"Knić",
				"Kragujevac",
				"Lapovo",
				"Paraćin",
				"Rača",
				"Rekovac",
				"Svilajnac",
				"Topola",
				"Ćuprija",
			},
		},
		"73": {
			Name: "Niš",
			Municipalities: []string{
				"Aleksinac",
				"Babušnica",
				"Bela Palanka",
				"Blace",
				"Dimitrovgrad",
				"Doljevac",
				"Gadžin Han",
				"Kuršumlija",
				"Merošina",
				"Niš",
				"Niška Banja",
				"Pirot",
				"Prokuplje",
				"Ražanj",
				"Svrljig",
				"Žitorađa",
			},
		},
		"74": {
			Name: "Južna Morava",
			Municipalities: []string{
				"Bojnik",
				"Bosilegrad",
				"Bujanovac",
				"Crna Trava",
				"Lebane",
				"Leskovac",
				"Medveđa",
				"Preševo",
				"Surdulica",
				"Trgovište",
				"Vladičin Han",
				"Vlasotince",
				"Vranje",
			},
		},
		"75": {
			Name: "Zaječar",
			Municipalities: []string{
				"Bor",
				"Boljevac",
				"Kladovo",
				"Knjaževac",
				"Majdanpek",
				"Negotin",
				"Sokobanja",
				"Zaječar",
			},
		},
		"76": {
			Name: "Podunavlje",
			Municipalities: []string{
				"Golubac",
				"Kučevo",
				"Malo Crniće",
				"Petrovac na Mlavi",
				"Požarevac",
				"Smederevo",
				"Smederevska Palanka",
				"Velika Plana",
				"Veliko Gradište",
				"Žabari",
				"Žagubica",
			},
		},
		"77": {
			Name: "Podrinje i Kolubara",
			Municipalities: []string{
				"Bogatić",
				"Koceljeva",
				"Krupanj",
				"Lajkovac",
				"Loznica",
				"Ljig",
				"Ljubovija",
				"Mali Zvornik",
				"Mionica",
				"Osečina",
				"Ub",
				"Valjevo",
				"Vladimirci",
				"Šabac",
			},
		},
		"78": {
			Name: "Kraljevo",
			Municipalities: []string{
				"Aleksandrovac",
				"Brus",
				"Gornji Milanovac",
				"Kraljevo",
				"Kruševac",
				"Lučani",
				"Novi Pazar",
				"Raška",
				"Sjenica",
				"Trstenik",
				"Tutin",
				"Varvarin",
				"Vrnjačka Banja",
				"Ćićevac",
				"Čačak",
			},
		},
		"79": {
			Name: "Užice",
			Municipalities: []string{
				"Arilje",
				"Bajina Bašta",
				"Ivanjica",
				"Kosjerić",
				"Nova Varoš",
				"Požega",
				"Priboj",
				"Prijepolje",
				"Užice",
				"Čajetina",
			},
		},
		"80": {
			Name: "Novi Sad",
			Municipalities: []string{
				"Bač",
				"Bačka Palanka",
				"Bački Petrovac",
				"Beočin",
				"Novi Sad",
				"Sremski Karlovci",
				"Temerin",
				"Titel",
				"Žabalj",
			},
		},
		"81": {
			Name:           "Sombor",
			Municipalities: []string{"Apatin", "Odžaci", "Sombor"},
		},
		"82": {
			Name: "Subotica",
			Municipalities: []string{
				"Ada",
				"Bačka Topola",
				"Kanjiža",
				"Kula",
				"Mali Iđoš",
				"Senta",
				"Subotica",
			},
		},
		"83": {
			Name:           "Bečej, Srbobran i Vrbas",
			Municipalities: []string{"Bečej", "Srbobran", "Vrbas"},
		},
		"84": {
			Name: "Kikinda",
			Municipalities: []string{
				"Kikinda",
				"Nova Crnja",
				"Novi Kneževac",
				"Čoka",
			},
		},
		"85": {
			Name: "Zrenjanin",
			Municipalities: []string{
				"Novi Bečej",
				"Sečanj",
				"Zrenjanin",
				"Žitište",
			},
		},
		"86": {
			Name: "Pančevo",
			Municipalities: []string{
				"Alibunar",
				"Kovačica",
				"Kovin",
				"Opovo",
				"Pančevo",
			},
		},
		"87": {
			Name:           "Vršac",
			Municipalities: []string{"Bela Crkva", "Plandište", "Vršac"},
		},
		"88": {
			Name: "Ruma",
			Municipalities: []string{
				"Inđija",
				"Irig",
				"Pećinci",
				"Ruma",
				"Stara Pazova",
			},
		},
		"89": {
			Name:           "Sremska Mitrovica",
			Municipalities: []string{"Sremska Mitrovica", "Šid"},
		},
	}
)
